"""settings

Revision ID: 588508c33ec3
Revises: 99870a299696
Create Date: 2021-12-30 01:28:22.718587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '588508c33ec3'
down_revision = '99870a299696'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('settings')
    # ### end Alembic commands ###
